Repository GSG-G10/RAM-News, pull requests merged in 2021-07, with the labels that each got.

#5 add readme content
  README.md
Labels: awaiting-review

#23 Header section
  css/common.css
  index.html
Labels: awaiting-review

#20 create details page comments
  css/details.css
  html/details.html
  images/avatar.png
Labels: done

#24 add baner section,responsive
  css/common.css
  css/style.css
  index.html
Labels: awaiting-review

#25 new post section html and responsive style
  css/common.css
  css/style.css
  index.html
Labels: awaiting-review

#22 News feed
  css/details.css
  html/details.html
Labels: done

#21 News title
  css/details.css
  html/details.html
Labels: request-change

#27 News section
  css/common.css
  css/style.css
  index.html
Labels: awaiting-review

#29 add code and style for footer section #18
  css/style.css
  index.html
Labels: awaiting-review

#28 add code and style for Most Read Sections #17
  css/style.css
  index.html
Labels: done

#26 add code and style for Featured section #16
  css/common.css
  css/style.css
  index.html
Labels: done

#32 Add header and footer to the details page
  html/details.html
Labels: awaiting-review

#35 edit featured position #31
  css/style.css
  index.html
Labels: done

#34 Add footer style common css file
  css/common.css
Labels: awaiting-review

#39 edit responsive featured-section #38
  css/common.css
  css/style.css
Labels: awaiting-review

#37 Edit images path
  index.html
Labels: awaiting-review

#42 edit icons-style
  css/common.css
Labels: done

#43 edit fonts size #40
  css/style.css
Labels: done

#51 add js to details page
  html/details.html
Labels: awaiting-review
